FROM balenalib/%%BALENA_MACHINE_NAME%%-node:9-stretch-build

#FROM resin/%%RESIN_MACHINE_NAME%%-python

#switch on systemd init system in container
ENV INITSYSTEM on

# pip install python deps from requirements.txt
# For caching until requirements.txt changes
COPY content/ /
RUN pip install -r /requirements.txt

COPY con



CMD ["python", "gpio_example.py"]
