FROM balenalib/%%BALENA_MACHINE_NAME%%-node:9-stretch-build

#FROM resin/%%RESIN_MACHINE_NAME%%-python

#switch on systemd init system in container
ENV INITSYSTEM on

COPY content/ /

RUN apt-get update \
 && apt-get install -yq \
 python-pip \
 python-smbus \
 python-dev \
 i2c-tools  \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*




RUN pip install -r /requirements.txt


CMD ["python", "gpio_example.py"]
