#!/bin/bash


/usr/src/app/temp_loop.py

# Allow any signal which would kill a process to stop server
trap "service cron stop" HUP INT QUIT ABRT ALRM TERM TSTP

while pgrep -u root temp > /dev/null; do sleep 5; done
